Algoritmo "CalculaVolume"


Var
   comprimento, largura, altura, volume: real


Inicio
      escreva("Informe o comprimento: ")
      leia(comprimento)
      
      escreva("Informe a largura: ")
      leia(largura)
      
      escreva("Informe o altura: ")
      leia(altura)
      
      volume <- comprimento * largura * altura
      
      escreva("Volume: ", volume, " cm3")


Fimalgoritmo