-- DROP DATABASE EMPRESA;

-- CREATE DATABASE EMPRESA;
-- USE EMPRESA;
	
CREATE TABLE EMPREGADO
(
	RG NUMERIC(10) CONSTRAINT PK_EMPREGADO  PRIMARY KEY,
	NOME VARCHAR(100) CONSTRAINT NN_NOME NOT NULL,
	CPF NUMERIC(11) CONSTRAINT UN_CPF UNIQUE,
	DEPARTAMENTO INT CONSTRAINT NN_DEPARTAMENTO NOT NULL,
	RGSUPERVISOR NUMERIC(10) CONSTRAINT FK_EMPREGADO REFERENCES EMPREGADO(RG),
	SALARIO NUMERIC(10,2) CONSTRAINT NN_SALARIO NOT NULL
);

CREATE TABLE DEPARTAMENTO
(
	NUMERO INT CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY IDENTITY (1,1),
	NOME VARCHAR(100) CONSTRAINT NN_NOME_DEP NOT NULL,
	RGGERENTE NUMERIC(10) CONSTRAINT NNRGERENTE NOT NULL CONSTRAINT FK_GERENTE REFERENCES EMPREGADO(RG)
);

CREATE TABLE PROJETO
(
	NUMERO INT CONSTRAINT PK_PROJETO PRIMARY KEY IDENTITY (1,1),
	NOME VARCHAR(100) CONSTRAINT NN_NOME_PROJETO NOT NULL,
	LOCALIZACAO VARCHAR(50) CONSTRAINT NN_LOCALIZACAO NOT NULL
);

CREATE TABLE DEPENDENTE
(
	NUMERODEPENDENTE INT CONSTRAINT PK_DEPENDENTE PRIMARY KEY IDENTITY(1,1),
	RGRESPONSAVEL NUMERIC(10),
	NOMEDEPENDENTE VARCHAR(100),
	CONSTRAINT UN_RGRESPONSAVELNOME UNIQUE (RGRESPONSAVEL,NOMEDEPENDENTE),
	CONSTRAINT FK_RGRESPONSAVEL FOREIGN KEY (RGRESPONSAVEL) REFERENCES EMPREGADO(RG),
	DTNASCIMENTO DATE CONSTRAINT NN_DTNASCIMENTO NOT NULL,
	RELACAO VARCHAR(30) CONSTRAINT NN_RELACAO NOT NULL,
	SEXO CHAR(1) CONSTRAINT CK_SEXO CHECK(SEXO IN('M','F')) NOT NULL
);

CREATE TABLE DEPARTAMENTOPROJETO
(
	NUMERODEPARTAMENTO INT,
	NUMEROPROJETO INT,
	CONSTRAINT PK_DEPARTAMENTOPROJETO PRIMARY KEY (NUMERODEPARTAMENTO,NUMEROPROJETO),
	CONSTRAINT FK_NUMERODEPARTAMENTO FOREIGN KEY (NUMERODEPARTAMENTO) REFERENCES DEPARTAMENTO(NUMERO),
	CONSTRAINT FK_NUMEROPROJETO FOREIGN KEY (NUMEROPROJETO) REFERENCES PROJETO(NUMERO)
);

CREATE TABLE EMPREGADOPROJETO
(
	RGEMPREGADO NUMERIC(10),
	NUMEROPROJETO INT,
	CONSTRAINT PK_EMPREGADOPROJETO PRIMARY KEY (RGEMPREGADO,NUMEROPROJETO),
	CONSTRAINT FK_RGEMPREGADO FOREIGN KEY (RGEMPREGADO) REFERENCES EMPREGADO(RG),
	CONSTRAINT FK_NUMEROPROJETO_EMPREGADOPROJETO FOREIGN KEY (NUMEROPROJETO) REFERENCES PROJETO(NUMERO),
	HORAS INT CONSTRAINT NN_HORAS NOT NULL
);

-- INSERTS

INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (10101010, 'Jo�o Luiz',11111111,1,null,3000.00);
INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (20202020, 'Fernando',22222222,2,10101010,2500.00);
INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (30303030, 'Ricardo',33333333,2,10101010,2300.00);
INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (40404040, 'Jorge',44444444,2,20202020,4200.00);
INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (50505050, 'Renato',55555555,3,20202020,1300.00);

INSERT INTO DEPARTAMENTO(NOME, RGGERENTE)
VALUES ('Contabilidade',10101010);
INSERT INTO DEPARTAMENTO(NOME, RGGERENTE)
VALUES ('Engenharia Civil',30303030);
INSERT INTO DEPARTAMENTO(NOME, RGGERENTE)
VALUES ('Engenharia Mec�nica',20202020);

ALTER TABLE EMPREGADO
ADD CONSTRAINT FK_DEPARTAMENTO_EMPREGADO FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO (NUMERO);

INSERT INTO PROJETO(NOME, LOCALIZACAO)
VALUES ('Financeiro 1', 'S�o Paulo');
INSERT INTO PROJETO(NOME, LOCALIZACAO)
VALUES ('Motor 3', 'Rio Claro');
INSERT INTO PROJETO(NOME, LOCALIZACAO)
VALUES ('Predio Central', 'Campinas');

INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(10101010,'Jorge','1986-12-27','Filho','M');
INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(10101010,'Luiz','1979-11-18','Filho','M');
INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(20202020,'Fernanda','1969-02-14','Conjuge','F');
INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(20202020,'Angelo','1995-02-10','Filho','M');
INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(30303030,'Andreia','1990-05-01','Filho','F');
										  
INSERT INTO DEPARTAMENTOPROJETO(NUMERODEPARTAMENTO,NUMEROPROJETO)
VALUES (2,1);
INSERT INTO DEPARTAMENTOPROJETO(NUMERODEPARTAMENTO,NUMEROPROJETO)
VALUES (3,2);
INSERT INTO DEPARTAMENTOPROJETO(NUMERODEPARTAMENTO,NUMEROPROJETO)
VALUES (2,3);

INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (20202020,1,10);
INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (20202020,2,20);
INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (30303030,1,35);
INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (40404040,3,50);
INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (50505050,3,35);