-- EXEMPLO  1
CREATE PROCEDURE SP_HELLO AS
BEGIN
	SELECT 'Hello World'
END

EXEC SP_HELLO

--EXEMPLO  2 - 
IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SP_Emprestimos' AND type = 'P') 
   DROP PROCEDURE SP_EMPRESTIMOS 
GO 
CREATE PROCEDURE SP_EMPRESTIMOS 
AS BEGIN
	SELECT NumEmp,
		   Quantia  
	FROM EMPRESTIMO
END 

EXEC SP_Emprestimos



-- EXEMPLO 3 - COM USO DE VARI�VEIS
CREATE PROCEDURE SP_HELLO1 AS
DECLARE @msg varchar (100)
BEGIN
	SELECT @msg = 'Hello World'
	PRINT @msg
END

EXEC SP_HELLO1

-- EXEMPLO 4 - COM PARAMETROS DE ENTRADA (INPUT)
CREATE or ALTER PROCEDURE SP_Contas 
(   @TIPO_CONTA INT, 
	@NUM_AGENCIA INT 
) 
AS BEGIN 
	SELECT C.NUMCONTA,
		   C.SALDO,
		   CLI.NOME,
		   CLI.CPF 
	FROM CONTA C
	INNER JOIN CONTA_CLIENTE CC ON C.NUMCONTA = CC.NUMCONTA
	INNER JOIN CLIENTE CLI ON CLI.CPF = CC.CPF 
	WHERE C.CODTIPO = @TIPO_CONTA AND C.NUMAGENCIA = @NUM_AGENCIA 
END 

EXEC SP_Contas 1, 1

-- EXEMPLO 5 - COM PARAMETROS DE SAIDA(OUTPUT)
CREATE PROCEDURE SP_TOTAL_EMPRESTIMOS 
   @NUMAGENCIA INT, 
   @TOTAL DECIMAL OUTPUT 
AS 
BEGIN 
	SELECT @TOTAL = SUM(QUANTIA) 
	FROM EMPRESTIMO
	WHERE NumAgencia = @NUMAGENCIA
END

-- EXEMPLO 6
EXEC SP_TOTAL_EMPRESTIMOS 2,NULL

DECLARE @TOTAL decimal
EXEC SP_TOTAL_EMPRESTIMOS 1, @TOTAL OUTPUT
print @TOTAL

-- EXEMPLO 7
DECLARE @TOTAL NUMERIC
EXEC SP_TOTAL_EMPRESTIMOS 1, @TOTAL OUTPUT
IF @TOTAL < 200 
BEGIN 
    SELECT 'Custo menor que 200 reais' 
END
ELSE 
 SELECT 'Custo ' + RTRIM(CAST(@TOTAL AS varchar(20)))

--EXEMPLO 8
CREATE OR ALTER PROCEDURE SP_CLIENTES
WITH ENCRYPTION
AS	
	SELECT NOME FROM CLIENTE

EXEC SP_CLIENTES

--EXEMPLO 9
IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SOMA' AND type = 'U') 
DROP TABLE SOMA
CREATE TABLE SOMA
(
	VALOR1 INT,
	VALOR2 INT
)
GO
CREATE PROCEDURE SP_CALCULASOMA
	@NUM INT
AS
	DECLARE @CONTADOR INT	
	SET @CONTADOR = 1
	DECLARE @soma INT
	SET @SOMA = 0
BEGIN
   WHILE (@CONTADOR <= @NUM)
	BEGIN
	   SET @SOMA = @SOMA + @CONTADOR
	   INSERT INTO SOMA VALUES (@CONTADOR, @SOMA)
	   SET @CONTADOR = @CONTADOR + 1
   	END
     	SELECT VALOR1,VALOR2 FROM SOMA
	DELETE from SOMA
END	

EXEC SP_CALCULASOMA 10
