CREATE DATABASE CONTROLE_PROJETOS;

USE CONTROLE_PROJETOS;

CREATE TABLE FUNCAO
(
	IDFUNCAO INT CONSTRAINT PK_IDFUNCAO PRIMARY KEY IDENTITY(1,1),
	NOMEFUNCAO VARCHAR(100) CONSTRAINT NN_NOMEFUNCAO NOT NULL
);

CREATE TABLE TIPOTAREFA
(
	IDTIPOTAREFA INT CONSTRAINT PK_IDTIPOTAREFA PRIMARY KEY IDENTITY(1,1),
	NOMETIPOTAREFA VARCHAR(100) CONSTRAINT NN_NOMETIPOTAREFA NOT NULL
);

CREATE TABLE STATUSTAREFA
(
	IDSTATUSTAREFA INT CONSTRAINT PK_IDSTATUSTAREFA PRIMARY KEY IDENTITY(1,1),
	NOMESTATUSTAREFA VARCHAR(100) CONSTRAINT NN_NOMESTATUSTAREFA NOT NULL
);

CREATE TABLE TIPOPROJETO
(
	IDTIPOPROJETO INT CONSTRAINT PK_IDTIPOPROJETO PRIMARY KEY IDENTITY(1,1),
	NOMETIPOPROJETO VARCHAR(100) CONSTRAINT NN_NOMETIPOPROJETO NOT NULL
);

CREATE TABLE STATUSPROJETO
(
	IDSTATUSPROJETO INT CONSTRAINT PK_IDSTATUSPROJETO PRIMARY KEY IDENTITY(1,1),
	NOMESTATUSPROJETO VARCHAR(100) CONSTRAINT NN_NOMESTATUSPROJETO NOT NULL
);

CREATE TABLE COLABORADOR
(
	IDCOLABORADOR INT CONSTRAINT PK_IDCOLABORADOR PRIMARY KEY IDENTITY(1,1),
	NOMECOLABORADOR VARCHAR(100) CONSTRAINT NN_NOMECOLABORADOR NOT NULL,
	CPF CHAR(11) CONSTRAINT NN_CPF NOT NULL,
	DATACONTRATACAO DATE CONSTRAINT NN_DATAINICIO NOT NULL,
	DATADESLIGAMENTO DATE,
);

CREATE TABLE PROJETO
(
	IDPROJETO INT CONSTRAINT PK_IDPROJETO PRIMARY KEY IDENTITY(1,1),
	NOMEPROJETO VARCHAR(100) CONSTRAINT NN_NOMEPROJETO NOT NULL,
	DURACAOPROJETO INT CONSTRAINT NN_DURACAOPROJETO NOT NULL,
	DATAINICIO DATE CONSTRAINT NN_DATAINICIO NOT NULL,
	DATATERMINOPREVISTA DATE CONSTRAINT NN_DATATERMINOPREVISTA NOT NULL,
	DATATERMINOREALIZADA DATE,
	IDTIPOPROJETO INT CONSTRAINT FK_IDTIPOPROJETO REFERENCES TIPOPROJETO(IDTIPOPROJETO) NOT NULL,
	IDSTATUSPROJETO INT CONSTRAINT FK_IDSTATUSPROJETO REFERENCES STATUSPROJETO(IDSTATUSPROJETO) NOT NULL,
	IDRESPONSAVEL INT CONSTRAINT FK_IDRESPONSAVEL REFERENCES COLABORADOR (IDCOLABORADOR) NOT NULL
);

CREATE TABLE COLABORADOR_FUNCAO
(
	IDCOLABORADOR INT CONSTRAINT FK_IDCOLABORADOR REFERENCES COLABORADOR (IDCOLABORADOR),
	IDFUNCAO INT CONSTRAINT FK_IDFUNCAO REFERENCES FUNCAO (IDFUNCAO),
	CONSTRAINT PK_COLABORADOR_FUNCAO PRIMARY KEY (IDCOLABORADOR,IDFUNCAO),
	DATAINICIO DATE CONSTRAINT NN_DATAINICIO NOT NULL,
	DATATERMINO DATE,
	MOTIVOTERMINOFUNCAO TEXT
);

CREATE TABLE TAREFA
(
	IDTAREFA INT CONSTRAINT PK_IDTAREFA PRIMARY KEY IDENTITY(1,1),
	DESCRICAOTAREFA VARCHAR(MAX) CONSTRAINT NN_DESCRICAOTAREFA NOT NULL, 
	IDTAREFADEPENDENTE INT CONSTRAINT FK_IDTAREFADEPENDENTE REFERENCES TAREFA(IDTAREFA), 
	IDPROJETO INT CONSTRAINT FK_IDPROJETO REFERENCES PROJETO(IDPROJETO) NOT NULL,
	IDTIPOTAREFA INT CONSTRAINT FK_IDTIPOTAREFA REFERENCES TIPOTAREFA(IDTIPOTAREFA) NOT NULL,
	IDSTATUSTAREFA INT CONSTRAINT FK_IDSTATUSTAREFA_TAREFA REFERENCES STATUSTAREFA(IDSTATUSTAREFA) NOT NULL
);

CREATE TABLE TAREFA_COLABORADOR_FUNCAO
(
	IDTAREFA INT CONSTRAINT FK_IDFUNCAO_TAREFA REFERENCES TAREFA (IDTAREFA),
	IDCOLABORADOR INT NOT NULL,
	IDFUNCAO INT NOT NULL, 
	CONSTRAINT FK_IDCOLABORADOR_FUNCAO FOREIGN KEY (IDCOLABORADOR,IDFUNCAO) REFERENCES COLABORADOR_FUNCAO (IDCOLABORADOR,IDFUNCAO),
	CONSTRAINT PK_TAREFA_COLABORADOR_FUNCAO PRIMARY KEY (IDTAREFA,IDCOLABORADOR,IDFUNCAO),
	DATAINICIOTAREFA DATETIME CONSTRAINT NN_DATAINICIOTAREFA NOT NULL,
	DATATERMINOTAREFAPREVISTA DATETIME CONSTRAINT NN_DATATERMINOTAREFAPREVISTA NOT NULL,
	DATATERMINOTAREFAREALIZADA DATETIME,
	IDSTATUSTAREFA INT CONSTRAINT FK_IDSTATUSTAREFA_COLABORADOR REFERENCES STATUSTAREFA(IDSTATUSTAREFA) NOT NULL,
	OBSERVACAO VARCHAR(MAX)
);


--INSERTS
INSERT INTO FUNCAO (NOMEFUNCAO) VALUES ('Analista de Sistemas');
INSERT INTO FUNCAO (NOMEFUNCAO) VALUES ('Desenvolvedor Backend');
INSERT INTO FUNCAO (NOMEFUNCAO) VALUES ('Desenvolvedor Frontend');
INSERT INTO FUNCAO (NOMEFUNCAO) VALUES ('Gerente de Projetos');
INSERT INTO FUNCAO (NOMEFUNCAO) VALUES ('Analista QA');

INSERT INTO TIPOTAREFA (NOMETIPOTAREFA) VALUES ('Planejamento');
INSERT INTO TIPOTAREFA (NOMETIPOTAREFA) VALUES ('Desenvolvimento');
INSERT INTO TIPOTAREFA (NOMETIPOTAREFA) VALUES ('Teste');
INSERT INTO TIPOTAREFA (NOMETIPOTAREFA) VALUES ('Revis�o de C�digo');
INSERT INTO TIPOTAREFA (NOMETIPOTAREFA) VALUES ('Documenta��o');

INSERT INTO STATUSTAREFA (NOMESTATUSTAREFA) VALUES ('Pendente');
INSERT INTO STATUSTAREFA (NOMESTATUSTAREFA) VALUES ('Em andamento');
INSERT INTO STATUSTAREFA (NOMESTATUSTAREFA) VALUES ('Conclu�da');
INSERT INTO STATUSTAREFA (NOMESTATUSTAREFA) VALUES ('Cancelada');
INSERT INTO STATUSTAREFA (NOMESTATUSTAREFA) VALUES ('Revis�o');

select * from STATUSTAREFA

INSERT INTO TIPOPROJETO (NOMETIPOPROJETO) VALUES ('Sistema Web');
INSERT INTO TIPOPROJETO (NOMETIPOPROJETO) VALUES ('Aplicativo M�vel');
INSERT INTO TIPOPROJETO (NOMETIPOPROJETO) VALUES ('Sistema ERP');
INSERT INTO TIPOPROJETO (NOMETIPOPROJETO) VALUES ('Dashboard BI');
INSERT INTO TIPOPROJETO (NOMETIPOPROJETO) VALUES ('Automa��o de Processos');

INSERT INTO STATUSPROJETO (NOMESTATUSPROJETO) VALUES ('Novo');
INSERT INTO STATUSPROJETO (NOMESTATUSPROJETO) VALUES ('Em execu��o');
INSERT INTO STATUSPROJETO (NOMESTATUSPROJETO) VALUES ('Conclu�do');
INSERT INTO STATUSPROJETO (NOMESTATUSPROJETO) VALUES ('Em pausa');
INSERT INTO STATUSPROJETO (NOMESTATUSPROJETO) VALUES ('Cancelado');

INSERT INTO COLABORADOR (NOMECOLABORADOR, CPF, DATACONTRATACAO, DATADESLIGAMENTO) VALUES ('Jo�o Silva', '12345678901', '2020-06-17', '2025-06-17');
INSERT INTO COLABORADOR (NOMECOLABORADOR, CPF, DATACONTRATACAO, DATADESLIGAMENTO) VALUES ('Maria Oliveira', '23456789012', '2022-06-11', '2023-06-30');
INSERT INTO COLABORADOR (NOMECOLABORADOR, CPF, DATACONTRATACAO, DATADESLIGAMENTO) VALUES ('Carlos Souza', '34567890123', '2024-06-10', NULL);
INSERT INTO COLABORADOR (NOMECOLABORADOR, CPF, DATACONTRATACAO, DATADESLIGAMENTO) VALUES ('Ana Lima', '45678901234', '2015-06-07', NULL);
INSERT INTO COLABORADOR (NOMECOLABORADOR, CPF, DATACONTRATACAO, DATADESLIGAMENTO) VALUES ('Paulo Mendes', '56789012345', '2023-06-09', NULL);

INSERT INTO PROJETO (NOMEPROJETO, DURACAOPROJETO, DATAINICIO, DATATERMINOPREVISTA, DATATERMINOREALIZADA, IDTIPOPROJETO, IDSTATUSPROJETO, IDRESPONSAVEL)
VALUES ('Projeto 1', 90, '2025-06-17', '2026-09-15', NULL, 1, 1, 1);
INSERT INTO PROJETO (NOMEPROJETO, DURACAOPROJETO, DATAINICIO, DATATERMINOPREVISTA, DATATERMINOREALIZADA, IDTIPOPROJETO, IDSTATUSPROJETO, IDRESPONSAVEL) 
VALUES ('Projeto 2', 100, '2025-02-10', '2025-10-10', NULL, 2, 2, 2);
INSERT INTO PROJETO (NOMEPROJETO, DURACAOPROJETO, DATAINICIO, DATATERMINOPREVISTA, DATATERMINOREALIZADA, IDTIPOPROJETO, IDSTATUSPROJETO, IDRESPONSAVEL) 
VALUES ('Projeto 3', 110, '2024-06-11', '2025-03-10', '2025-04-11', 3, 3, 3);
INSERT INTO PROJETO (NOMEPROJETO, DURACAOPROJETO, DATAINICIO, DATATERMINOPREVISTA, DATATERMINOREALIZADA, IDTIPOPROJETO, IDSTATUSPROJETO, IDRESPONSAVEL) 
VALUES ('Projeto 4', 120, '2025-10-10', '2026-09-15', NULL, 4, 4, 4);
INSERT INTO PROJETO (NOMEPROJETO, DURACAOPROJETO, DATAINICIO, DATATERMINOPREVISTA, DATATERMINOREALIZADA, IDTIPOPROJETO, IDSTATUSPROJETO, IDRESPONSAVEL) 
VALUES ('Projeto 5', 130, '2023-06-17', '2024-09-15', '2025-02-02', 5, 5, 5);

INSERT INTO COLABORADOR_FUNCAO (IDCOLABORADOR, IDFUNCAO, DATAINICIO, DATATERMINO, MOTIVOTERMINOFUNCAO) 
VALUES (1, 1, '2025-03-17', NULL, NULL);
INSERT INTO COLABORADOR_FUNCAO (IDCOLABORADOR, IDFUNCAO, DATAINICIO, DATATERMINO, MOTIVOTERMINOFUNCAO) 
VALUES (2, 2, '2024-02-16', '2025-03-14', 'Falta de comprometimento');
INSERT INTO COLABORADOR_FUNCAO (IDCOLABORADOR, IDFUNCAO, DATAINICIO, DATATERMINO, MOTIVOTERMINOFUNCAO) 
VALUES (3, 3, '2025-01-15', NULL, NULL);
INSERT INTO COLABORADOR_FUNCAO (IDCOLABORADOR, IDFUNCAO, DATAINICIO, DATATERMINO, MOTIVOTERMINOFUNCAO) 
VALUES (4, 4, '2024-04-14', '2025-05-14', 'Solicitou desligamento');
INSERT INTO COLABORADOR_FUNCAO (IDCOLABORADOR, IDFUNCAO, DATAINICIO, DATATERMINO, MOTIVOTERMINOFUNCAO) 
VALUES (5, 5, '2025-06-01', NULL, NULL);

INSERT INTO TAREFA (DESCRICAOTAREFA, IDTAREFADEPENDENTE, IDPROJETO, IDTIPOTAREFA, IDSTATUSTAREFA) 
VALUES ('Tarefa 1', NULL, 1, 1, 1);
INSERT INTO TAREFA (DESCRICAOTAREFA, IDTAREFADEPENDENTE, IDPROJETO, IDTIPOTAREFA, IDSTATUSTAREFA) 
VALUES ('Tarefa 2', 1, 2, 2, 2);
INSERT INTO TAREFA (DESCRICAOTAREFA, IDTAREFADEPENDENTE, IDPROJETO, IDTIPOTAREFA, IDSTATUSTAREFA) 
VALUES ('Tarefa 3', 2, 3, 3, 3);
INSERT INTO TAREFA (DESCRICAOTAREFA, IDTAREFADEPENDENTE, IDPROJETO, IDTIPOTAREFA, IDSTATUSTAREFA) 
VALUES ('Tarefa 4', 3, 4, 4, 4);
INSERT INTO TAREFA (DESCRICAOTAREFA, IDTAREFADEPENDENTE, IDPROJETO, IDTIPOTAREFA, IDSTATUSTAREFA) 
VALUES ('Tarefa 5', 4, 5, 5, 5);

INSERT INTO TAREFA_COLABORADOR_FUNCAO (IDTAREFA, IDCOLABORADOR, IDFUNCAO, DATAINICIOTAREFA, DATATERMINOTAREFAPREVISTA, DATATERMINOTAREFAREALIZADA, IDSTATUSTAREFA, OBSERVACAO)
VALUES (1, 3, 3, '2025-02-01 08:50:00', '2025-02-03 18:00:00', '2025-02-03 18:50:00', 1, 'Sem observa��es');
INSERT INTO TAREFA_COLABORADOR_FUNCAO (IDTAREFA, IDCOLABORADOR, IDFUNCAO, DATAINICIOTAREFA, DATATERMINOTAREFAPREVISTA, DATATERMINOTAREFAREALIZADA, IDSTATUSTAREFA, OBSERVACAO) 
VALUES (2, 4, 4, '2025-02-02 08:50:00', '2025-02-04 18:00:00', '2025-02-04 16:45:00', 2, 'Sem observa��es');
INSERT INTO TAREFA_COLABORADOR_FUNCAO (IDTAREFA, IDCOLABORADOR, IDFUNCAO, DATAINICIOTAREFA, DATATERMINOTAREFAPREVISTA, DATATERMINOTAREFAREALIZADA, IDSTATUSTAREFA, OBSERVACAO) 
VALUES (3, 5, 5, '2025-02-03 08:50:00', '2025-02-05 18:00:00', '2025-02-06 12:33:00', 3, 'Sem observa��es');
INSERT INTO TAREFA_COLABORADOR_FUNCAO (IDTAREFA, IDCOLABORADOR, IDFUNCAO, DATAINICIOTAREFA, DATATERMINOTAREFAPREVISTA, DATATERMINOTAREFAREALIZADA, IDSTATUSTAREFA, OBSERVACAO) 
VALUES (4, 1, 1, '2025-02-04 08:50:00', '2025-02-06 18:00:00', '2025-02-07 14:37:00', 4, 'Sem observa��es');
INSERT INTO TAREFA_COLABORADOR_FUNCAO (IDTAREFA, IDCOLABORADOR, IDFUNCAO, DATAINICIOTAREFA, DATATERMINOTAREFAPREVISTA, DATATERMINOTAREFAREALIZADA, IDSTATUSTAREFA, OBSERVACAO) 
VALUES (5, 2, 2, '2025-02-05 08:50:00', '2025-18-07 18:00:00', '2025-18-08 13:03:43', 5, 'Sem observa��es');
